# $OpenBSD: Makefile.template,v 1.85 2019/09/09 19:19:05 kmos Exp $

COMMENT=		name your accessors get_foo() and set_foo()

DISTNAME=		MooseX-FollowPBP-0.05

CATEGORIES=		devel

# Artistic 2.0
PERMIT_PACKAGE=		Yes

MODULES=		cpan

RUN_DEPENDS=		devel/p5-Moose

PKG_ARCH=		*

.include <bsd.port.mk>
