# $OpenBSD: Makefile,v 1.42 2019/11/03 14:07:41 jasper Exp $

COMMENT =	simple .ini-file format

DISTNAME =	Config-INI-0.025
CATEGORIES =	devel

MODULES =	cpan
PKG_ARCH =	*

# Perl
PERMIT_PACKAGE =	Yes

CPAN_AUTHOR =		SHLOMIF

CONFIGURE_STYLE =	modbuild

RUN_DEPENDS =		devel/p5-Mixin-Linewise>=0.105

.include <bsd.port.mk>
