# $OpenBSD$

COMMENT =	teach ->new to accept single, non-hashref arguments

DISTNAME =	MooseX-OneArgNew-0.005

CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

.include <bsd.port.mk>
