# $OpenBSD$

COMMENT =	Apache::Test change logfile

DISTNAME =	Apache-Test-1.42

CATEGORIES =	cpan

# license field not set, consider bugging module's author
PERMIT_PACKAGE =	unknown license
PERMIT_DISTFILES =	unknown license

MODULES =		cpan

RUN_DEPENDS =		cpan/p5-Win32-Process

PKG_ARCH =		*

.include <bsd.port.mk>
