# $OpenBSD: Makefile.template,v 1.85 2019/09/09 19:19:05 kmos Exp $

COMMENT =	CSS Selector to XPath compiler

DISTNAME =	HTML-Selector-XPath-0.25

CATEGORIES =	www

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

TEST_DEPENDS =		devel/p5-Test-Base \
			sysutils/p5-Capture-Tiny

CONFIGURE_STYLE =	perl modinst

PKG_ARCH =		*

.include <bsd.port.mk>
