# $OpenBSD: Makefile.template,v 1.85 2019/09/09 19:19:05 kmos Exp $

COMMENT =	multivalue-property package-oriented configuration

DISTNAME =	Config-MVP-2.200011

CATEGORIES =	devel

# Perl
PERMIT_PACKAGE =	Yes

MODULES =		cpan

.include <bsd.port.mk>
