# $OpenBSD: Makefile,v 1.5 2019/10/29 01:20:28 afresh1 Exp $

COMMENT =		Call isa, can, does and DOES safely on things that may not

MODULES =		cpan
PKG_ARCH =		*
DISTNAME =		Safe-Isa-1.000010
CATEGORIES =		devel
FIX_EXTRACT_PERMISSIONS =	Yes

# Perl
PERMIT_PACKAGE =	Yes

.include <bsd.port.mk>
